Thesis/Thesis/Models/GamingEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Thesis.Models
{
    public class GamingEvent
    {
        public int GamingEventId { get; set; }
        public int CategoryEventId { get; set; }

        public string UserId { get; set; }
        public virtual ApplicationUser Publisher { get; set; }

        [Required(ErrorMessage = "Proszę dodać tytuł wydarzenia")]
        [StringLength(75, ErrorMessage = "Tytul nie moze miec wiecej niz 150 znakow")]
        [DisplayName("Tytuł")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Proszę dodać opis wydarzenia")]
        [StringLength(1000, ErrorMessage = "Tytul nie moze miec wiecej niz 1000 znakow")]
        [DisplayName("Opis")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        //TODO: Dodać date
        public DateTime DateOfEvent { get; set; }
        public int MaxNumberOfPeople { get; set; }
        public int CurrentNumberOfPeople { get; set; }

        [DisplayName("Główny obrazek")]
        public string MainPicture { get; set; }

        public virtual CategoryEvent CategoryEvent { get; set; }
        public virtual ICollection<ImageEvent> ImageEvent { get; set; }
        public virtual ICollection<CommentEvent> Comments { get; set; }

        [InverseProperty("AttendGamingEvent")]
        public virtual ICollection<ApplicationUser> UsersToAttend { get; set; }
    }
}

Thesis/Thesis/Controllers/GamingEventController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Migrations;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thesis.DAL;
using Thesis.Helpers.AI.SentimentalAnalisys;
using Thesis.Helpers.AI.SpamDetection;
using Thesis.Helpers.Procedural;
using Thesis.Infrastructure;
using Thesis.Models;
using Thesis.ViewModels;

namespace Thesis.Controllers
{
    public class GamingEventController : Controller
    {
        private ThesisContext context = new ThesisContext();

        public Func<string> GetUserId; //For testing
        public GamingEventController()
        {
            GetUserId = () => User.Identity.GetUserId();
        }

        // GET: GamingEvent
        public ActionResult Index(string nameOfEventCategory = null)
        {
            var events = nameOfEventCategory != null ? context.GamingEvents.Where(a => a.CategoryEvent.Name == nameOfEventCategory).ToList() :
                                                    context.GamingEvents.ToList();

            ApplicationUser user = null;
            string id = GetUserId();
            if (id != string.Empty && id != null)
                user = context.Users.Where(a => a.Id == id).First();



            GameEventViewModel vm = new GameEventViewModel
            {
                LoggedUser = user,
                GamingEvents = events
            };

            return View(vm);
        }

        [ChildActionOnly]
        public PartialViewResult MenuCategoryEvents()
        {
            //without interface use : HttpContext.Cache.Add("Some value");
            ICache abstractCache = new AbstractCache();

            List<GamingEvent> randomEvents;
            List<CategoryEvent> gameEventsCategories;

            if (abstractCache.IsSet(ConfigurationManager.AppSettings["RandomEventOffer"]))
            {
                randomEvents = abstractCache.Get(ConfigurationManager.AppSettings["RandomEventOffer"]) as List<GamingEvent>;
            }
            else
            {
                randomEvents = context.GamingEvents.OrderByDescending(g => Guid.NewGuid()).Take(3).ToList();
                abstractCache.Set(ConfigurationManager.AppSettings["RandomEventOffer"], randomEvents, 60);
            }

            if (abstractCache.IsSet(ConfigurationManager.AppSettings["GameEventsCategories"]))
            {
                gameEventsCategories = abstractCache.Get(ConfigurationManager.AppSettings["GameEventsCategories"]) as List<CategoryEvent>;
            }
            else
            {
                gameEventsCategories = context.CategoryEvents.ToList();
                abstractCache.Set(ConfigurationManager.AppSettings["GameEventsCategories"], gameEventsCategories, 1440);
            }


            var vm = new GameEventCategoryMenuViewModel()
            {
                GamingEvents  = randomEvents,
                CategoryEvents = gameEventsCategories
            };

            return PartialView("_MenuCategoryGameEvents", vm);
        }
    
        public JsonResult AddUserToGameEvent(int gameEventId = 1)
        {
            var gameEvent = context.GamingEvents.Where(a => a.GamingEventId == gameEventId).First();

            ApplicationUser user = null;
            string id = User.Identity.GetUserId();
            if (id != string.Empty && id != null)
                user = context.Users.Where(a => a.Id == id).First();

            gameEvent.UsersToAttend.Add(user);
            user.AttendGamingEvent.Add(gameEvent);
            context.SaveChanges();

            return Json(gameEvent.UsersToAttend.Select(x => new
            {
                userName = x.UserName
            }), JsonRequestBehavior.AllowGet);
        }

        public JsonResult RemoveUserFromGameEvent(int gameEventId = 1)
        {
            var gameEvent = context.GamingEvents.Where(a => a.GamingEventId == gameEventId).First();

            ApplicationUser user = null;
            string id = User.Identity.GetUserId();
            if (id != string.Empty && id != null)
                user = context.Users.Where(a => a.Id == id).First();

            gameEvent.UsersToAttend.Remove(user);
            user.AttendGamingEvent.Remove(gameEvent);
            context.SaveChanges();

            return Json(gameEvent.UsersToAttend.Select(x => new
            {
                userName = x.UserName
            }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddEvent()
        {
            var vm = new EventCategoryViewModel()
            {
                EventCategory = context.CategoryEvents.ToList(),
                GamingEvent = new GamingEvent()
            };
            return View("~/Views/GamingEvent/AddGameEvent.cshtml", vm);
        }

        public ActionResult EditEvent(int id)
        {
            var gameEvent = context.GamingEvents.Find(id);
            if (gameEvent == null)
                return RedirectToAction("Index", new { errorMessage = "Nie ma takiego eventu" });

            var vm = new EventCategoryViewModel()
            {
                EventCategory = context.CategoryEvents.ToList(),
                GamingEvent =gameEvent
            };

            return View("~/Views/GamingEvent/EditGameEvent.cshtml", vm);
        }


        [HttpPost]
        public ActionResult SaveEvent(EventCategoryViewModel vm, HttpPostedFileBase file, string newItem = null)
        {
            if (SpamDetector.IsContentSpam(vm.GamingEvent.Title))
                return RedirectToAction("Index", "Post");
            //Verify whether user has neccessary data 
            ApplicationUser user = null;
            string id = User.Identity.GetUserId();
            if (id != string.Empty && id != null)
                user = context.Users.Where(a => a.Id == id).First();


            int idd = vm.GamingEvent.GamingEventId;

            var gameEvent = vm.GamingEvent;
            if (file != null && file.ContentLength > 0)
            {
                if (Path.GetExtension(file.FileName).ToLower() == ".jpg" || Path.GetExtension(file.FileName).ToLower() == ".png")
                {
                    var sourceImage = Image.FromStream(file.InputStream);

                    sourceImage = ResizeImage(sourceImage, 500, 500);

                    //Generowanie plik
                    var fileExt = Path.GetExtension(file.FileName);
                    var filename = Guid.NewGuid() + fileExt; // Unikalny identyfikator + rozszerzenie

                    //W jakim folderze ma byc umiesczony dany plik oraz jego nazwa! Oraz zapis
                    var path = Path.Combine(Server.MapPath(AppConfig.ImagesGamingEventFolder), filename);
                    //file.SaveAs(path);
                    sourceImage.Save(path);
                    gameEvent.MainPicture = filename;
                }

            }
            else if (file == null && newItem != null && newItem != String.Empty)
            {
                var fractImg = FractalGenerator.GenereateFractal1(user.Email);
                var filename = Guid.NewGuid() + ".jpg";
                var path = Path.Combine(Server.MapPath(AppConfig.ImagesGamingEventFolder), filename);
                fractImg.Save(path);
                gameEvent.MainPicture = filename;
            }

            gameEvent.UserId = user.Id;
            gameEvent.Publisher = user;

            context.GamingEvents.AddOrUpdate(gameEvent);
            context.SaveChanges();

            return RedirectToAction("Events", "Manage");
        }

        [HttpPost]
        public string DeleteEvent(int? id)
        {
            var gameEvent = context.GamingEvents.Find(id);
            if (gameEvent != null)
            {
                context.GamingEvents.Remove(gameEvent);
                context.SaveChanges();
                return "Ok";
            }
            else
                return null;
        }

        [NonAction]
        public static Bitmap ResizeImage(Image image, int width, int height)
        {
            var destRect = new Rectangle(0, 0, width, height);
            var destImage = new Bitmap(width, height);

            destImage.SetResolution(image.HorizontalResolution, image.VerticalResolution);

            using (var graphics = Graphics.FromImage(destImage))
            {
                graphics.CompositingMode = CompositingMode.SourceCopy;
                graphics.CompositingQuality = CompositingQuality.HighQuality;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.SmoothingMode = SmoothingMode.HighQuality;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;

                using (var wrapMode = new ImageAttributes())
                {
                    wrapMode.SetWrapMode(WrapMode.TileFlipXY);
                    graphics.DrawImage(image, destRect, 0, 0, image.Width, image.Height, GraphicsUnit.Pixel, wrapMode);
                }
            }

            return destImage;
        }


        [HttpPost]
        public PartialViewResult AddComment(int gamingEventId, string content)
        {
            if (SpamDetector.IsContentSpam(content))
                return null;

            var gameEvent = context.GamingEvents.Where(a => a.GamingEventId == gamingEventId).First();
            ApplicationUser user = null;
            string id = User.Identity.GetUserId();
            if (id != string.Empty && id != null)
                user = context.Users.Where(a => a.Id == id).First();

            CommentEvent commentEvent = new CommentEvent()
            { Body = content, DateOfInsert = DateTime.Now, GamingEventId = gameEvent.GamingEventId,
                UserId = User.Identity.GetUserId(), User = user };

            var sentimentalInt = new SentimentalInterpreter();

Thesis/Thesis/Views/GamingEvent/Index.cshtml
@model Thesis.ViewModels.GameEventViewModel
@using Thesis.Infrastructure

@{
    ViewBag.Title = "Index";
}

@Html.Action("MenuCategoryEvents")

<div id="content-wrapper">
    <div class="container-fluid">
        @Html.Partial("_ListOfEvents")
    </div>
</div>

<div id="modalSpamWarning" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Wykryty Spam</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Przykro nam, ale ten tekst jest podejrzany o bycie spamem proszę wprowadzić inny</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Zamknij</button>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script>
        function addToGameEvent(id)
        {
            $gameEventId = id;

            if ($gameEventId != 0)
            {
                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("AddUserToGameEvent", "GamingEvent")',
                    data: { gameEventId: $gameEventId},
                success: function (result)
                {
                    $("#" + $gameEventId).attr("onclick", "removeFromGameEvent(this.id)");
                    $("#" + $gameEventId).removeClass("btn-success").addClass("btn-danger");
                    $("#" + $gameEventId).text("Odejdź od wydarzenia");

                    $("#collapseExample-" + $gameEventId).empty();
                    if (result.length > 0) {
                        for (i = 0; i < result.length; i++) {
                            $("#collapseExample-" + $gameEventId).append('<li class="list-group-item">' + result[i].userName + '</li>');
                        }
                    }
                    else {
                        $("#collapseExample-" + $gameEventId).append('<li class="list-group-item">Brak użytkowników</li>');
                    }
                },
            });
            }
        }

        function removeFromGameEvent(id)
        {
            $gameEventId = id;

            if ($gameEventId != 0)
            {
                $.ajax({
                    contentType: 'application/json; charset=utf-8',
                url: '@Url.Action("RemoveUserFromGameEvent", "GamingEvent")',
                    data: { gameEventId: $gameEventId},
                success: function (result)
                {
                    $("#" + $gameEventId).attr("onclick", "addToGameEvent(this.id)");
                    $("#" + $gameEventId).removeClass("btn-danger").addClass("btn-success");
                    $("#" + $gameEventId).text("Dołącz do wydarzenia");

                    $("#collapseExample-" + $gameEventId).empty();
                    if (result.length > 0) {
                        for (i = 0; i < result.length; i++) {
                            $("#collapseExample-" + $gameEventId).append('<li class="list-group-item">' + result[i].userName + '</li>');
                        }
                    }
                    else {
                        $("#collapseExample-" + $gameEventId).append('<li class="list-group-item">Brak użytkowników</li>');
                    }
                },
            });
            }
        }



        function addComment(id)
        {
            $gameEventId = id.split("-")[1];
            $content = "";
            $isSpam = false;


            if ($.isNumeric($gameEventId)) {
                $textArea = $('#textArea-addComment-' + $gameEventId);
                $content = $textArea.val();
            }
            else {
                alert("Błąd");
            }

             $.ajax({
                async: false,
                url: '@Url.Action("IsSpam", "Home")',
                data: { text: $content},
                success: function (response)
                {
                    if (response == true)
                        $isSpam = true;
                },
            });

            if ($isSpam) {
                $('#modalSpamWarning').modal();
                return;
            }

              $.ajax({
                type: "POST",
                url: '@Url.Action("AddComment", "GamingEvent")',
                  data: { gamingEventId: $gameEventId, content: $content},
                success: function (response)
                {
                    $('#collapseComments-' + $gameEventId).replaceWith(response);
                    $('#collapseComments-' + $gameEventId).collapse('show');
                    scrollToElement();

                },
            });
        }


        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        async function scrollToElement() {
            await sleep(500);
            var spanElement = document.getElementById("lastElement");
            spanElement.scrollIntoView({ behavior: "smooth", block: "start", inline: "nearest" });


            var element = spanElement.nextSibling.nextSibling;

            var originalColor = getComputedStyle(element).backgroundColor; // Store original color (red)

            $jqueryElement = $(element);

            $jqueryElement.css({ "background-color": "#fff596", "transition": "background-color 0.5s ease" });

            setTimeout(function () {
                $jqueryElement.css("background-color", originalColor);
            }, 3000);

        }

        async function scrollToElementComment(id) {
            await sleep(500);
            var spanElement = document.getElementById('commentDiv-' + id);
            //Tutaj skończyłem

            var nodes = spanElement.querySelectorAll(".media-body");
            var lastElement = nodes[nodes.length - 1];
            lastElement.scrollIntoView({ behavior: "smooth", block: "start", inline: "nearest" });


            var originalColor = getComputedStyle(lastElement).backgroundColor; // Store original color (red)

            $jqueryElement = $(lastElement);

            $jqueryElement.css({ "background-color": "#fff596", "transition": "background-color 0.5s ease" });

            setTimeout(function () {
                $jqueryElement.css("background-color", originalColor);
            }, 1500);



        }



           function likedComment(ele) {
            var $button = $(ele);
            $id = $button.attr('id');

            $commentId = $id.split("-")[1];

            $.ajax({
                type: "GET",
                 url: '@Url.Action("LikeGameEventComment", "Comment")',
                data: { commentId: $commentId },
                success: function (response)
                {
                    $('#comment-likes-of-' + $commentId).text(response.amount);
                    if (response.isNewComment) {
                        $('#comment-likes-of-' + $commentId).closest("span").find("img").attr("src", "@Url.ImagesOtherPath("LikedComment.svg")");
                    }
                    else {
                        $('#comment-likes-of-' + $commentId).closest("span").find("img").attr("src", "@Url.ImagesOtherPath("like.svg")");
                    }
                },
            });
        }

         function addChildrenComment(ele,isFirst) {
            var $button = $(ele);
            $idOfParentId = $button.val();
            $contentOfComment = $('#addCommentFor-' + $idOfParentId).val();
            
            if ($.trim($contentOfComment))
            {
                $isSpam = false;

                 $.ajax({
                    async: false,
                    url: '@Url.Action("IsSpam", "Home")',
                    data: { text: $content},
                    success: function (response)
                    {
                        if (response == true)
                            $isSpam = true;
                    },
                });

                if ($isSpam) {
                    $('#modalSpamWarning').modal();
                    return;
                }

                $.ajax({
                    url: '@Url.Action("AddChildCommentEvent", "Comment")',
                    data: { idOfParentId: $idOfParentId, content: $contentOfComment },
                    success: function (response)
                    {
                        if (isFirst) {
                            $('#commentDiv-' + $idOfParentId).parent().replaceWith(response);
                        }
                        else {
                            $('#commentDiv-' + $idOfParentId).replaceWith(response);
                        }

                        scrollToElementComment($idOfParentId);

                    }
                });
            }
        }

        function unLikedComment(ele) {
            var $button = $(ele);
            $id = $button.attr('id');

            $commentId = $id.split("-")[1];

            $.ajax({
                type: "GET",
                 url: '@Url.Action("UnLikeGameEventComment", "Comment")',
                data: { commentId: $commentId },
                success: function (response) {
                    $('#comment-unlikes-of-' + $commentId).text(response.amount);


                    if (response.isNewComment) {
                        $('#comment-unlikes-of-' + $commentId).closest("span").find("img").attr("src", "@Url.ImagesOtherPath("unlikeComment.svg")");
                    }
                    else {
                        $('#comment-unlikes-of-' + $commentId).closest("span").find("img").attr("src", "@Url.ImagesOtherPath("dislike.svg")");
                    }
                },
            });
        }


    </script>
}

Thesis/Thesis/Views/GamingEvent/_ChildrenComments.cshtml
@model Thesis.ViewModels.CurrentCommentGameEventViewModel
@using Thesis.Infrastructure



<div class="media mt-3" id="commentDiv-@Model.Com.CommentEventId">
    @if (Model.Com.User.MainPicture != null)
    {
        <img src="@Url.ImagesUserPath(Model.Com.User.MainPicture)" width="32" class="mr-3 img-fluid rounded">
    }
    else
    {
        <img src="@Url.ImagesUserPath("user.png")" class="mr-3 img-fluid">
    }
    <div class="media-body">
        <h6 class="mt-0">@Model.Com.User.UserName</h6>
        <strong>@Model.Com.DateOfInsert</strong>
        @if (Model.Com.IsHappy)
        {
            <img src="@Url.ImagesOtherPath("isHappy.svg")" />
        }
        <p>
            @Model.Com.Body <br />
            <span @if (User.Identity.IsAuthenticated) { <text> onclick="likedComment(this)" id="likeComment-@Model.Com.CommentEventId" value="@Model.Com.CommentEventId" class="commentLike" </text> }>
                @if (Model.LoggedUser != null && Model.LoggedUser.LikedCommentsEvents.Contains(Model.Com))
                {
                    <img src="@Url.ImagesOtherPath("LikedComment.svg")" /> <strong id="comment-likes-of-@Model.Com.CommentEventId">@Model.Com.Likes</strong>
                }
                else
                {
                    <img src="@Url.ImagesOtherPath("like.svg")" /> <strong id="comment-likes-of-@Model.Com.CommentEventId">@Model.Com.Likes</strong>
                }
            </span>
            <span @if (User.Identity.IsAuthenticated) { <text> onclick="unLikedComment(this)" id="unLikeComment-@Model.Com.CommentEventId" value="@Model.Com.CommentEventId" class="commentUnLike" </text> }>
                @if (Model.LoggedUser != null && Model.LoggedUser.UnlikeCommentEvents.Contains(Model.Com))
                {
                    <img src="@Url.ImagesOtherPath("unlikeComment.svg")" /> <strong id="comment-unlikes-of-@Model.Com.CommentEventId"> @Model.Com.UnLikes</strong>
                }
                else
                {
                    <img src="@Url.ImagesOtherPath("dislike.svg")" /> <strong id="comment-unlikes-of-@Model.Com.CommentEventId"> @Model.Com.UnLikes</strong>
                }
            </span>

            <div class="row">
                <div class="input-group mb-2">
                    <div class="col-12 col-lg-9">
                        <textarea id="addCommentFor-@Model.Com.CommentEventId" class="form-control" placeholder="Twój komentarz" rows="1"></textarea>
                    </div>
                    <div class="col-12 col-lg-3">
                        <button value="@Model.Com.CommentEventId" onclick="addChildrenComment(this,false)" class="btn btn-primary btn-block">Dodaj komentarz</button>
                    </div>
                </div>
            </div>
        </p>

        @if (Model.Com.Children != null && Model.Com.Children.Count > 0)
        {
            foreach (var childCom in Model.Com.Children)
            {
                @Html.Action("ChildrenEventComment", "GamingEvent", new { childCom })
            }
        }

    </div>
</div>

Thesis/Thesis/Views/GamingEvent/_GameEventData.cshtml
@model Thesis.ViewModels.EventCategoryViewModel
@using Thesis.Infrastructure;

@using (@Html.BeginForm("SaveEvent", "GamingEvent", FormMethod.Post, new { enctype = "multipart/form-data", @id = "myform" }))
{
    if (ViewData.ContainsKey("NewBook"))
    {
        <input type="hidden" name="newItem" value="New Book" />
    }

    @Html.AntiForgeryToken()

    <div class="form-group text-danger">
        @Html.ValidationSummary()
    </div>

    @Html.HiddenFor(o => o.GamingEvent.GamingEventId)
    @Html.HiddenFor(o => o.GamingEvent.MainPicture)


    <div class="form-row">
        <div class="col-lg-3 mb-3">
            @Html.LabelFor(o => o.GamingEvent.Title, "Tytuł:")
            @Html.TextBoxFor(o => o.GamingEvent.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(o => o.GamingEvent.Title, null, new { @class = "form-text text-danger" })
        </div>



        <div class="col-lg-3 mb-3">
            @Html.LabelFor(o => o.GamingEvent.DateOfEvent, "Data wydarzenia:")
            @Html.TextBoxFor(o => o.GamingEvent.DateOfEvent, new { @class = "form-control date", @id = "dateOfEvent" })
            @Html.ValidationMessageFor(o => o.GamingEvent.DateOfEvent, null, new { @class = "form-text text-danger" })
        </div>

        <div class="col-lg-3 mb-3">
            @Html.LabelFor(o => o.EventCategory, "Kategoria:")<br />
            @Html.DropDownListFor(m => m.GamingEvent.CategoryEventId, new SelectList(Model.EventCategory, "CategoryEventId", "Name", Model.EventCategory.First().CategoryEventId), new { @class = "form-control" })
        </div>

        <div class="col-lg-3 mb-3">
            @Html.LabelFor(o => o.GamingEvent.MaxNumberOfPeople, "Maksymalna ilość osób:")
            @Html.TextBoxFor(o => o.GamingEvent.MaxNumberOfPeople, new { @class = "form-control" })
            @Html.ValidationMessageFor(o => o.GamingEvent.MaxNumberOfPeople, null, new { @class = "form-text text-danger" })
        </div>
    </div>

    <div class="form-row">
        <div class="col-lg-12 mb-3">
            @Html.LabelFor(o => o.GamingEvent.Content, "Opis:")
            @Html.TextAreaFor(o => o.GamingEvent.Content, new { @class = "form-control", @rows = "3" })
            @Html.ValidationMessageFor(o => o.GamingEvent.Content, null, new { @class = "form-text text-danger" })
        </div>
    </div>

    <div class="form-row">
        @if (Model.GamingEvent.MainPicture != null)
        {
            <div class="col-lg-6 mb-3">
                <div class="col-12">
                    <div class="col-12">
                        <label class="btn btn-primary btn-block" for="my-file-selector">
                            <input id="my-file-selector" name="file" type="file" style="display:none"
                                   onchange="realUrl(this)">
                            Wybierz zdjęcie
                        </label>
                    </div>
                    <div class="col-12 text-center">
                        <span class='label label-info font-weight-bold' id="upload-file-info"></span>
                    </div>
                </div>
                <div class="col-12">
                    <div class="col-12">Nowy obrazek</div>
                    <div class="col-12">
                        <img id="userNewImage" src="@Url.ImagesOtherPath("mNnZ.png")" class="img-fluid" alt="your image" />
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-3">
                <div class="col-12 text-center">
                    <p>
                        Obecny obrazek
                    </p>
                </div>
                <div class="col-12 text-center">
                    <img class="img-fluid" src="@Url.ImagesGamingEventPath(Model.GamingEvent.MainPicture)" />
                </div>
            </div>
        }
        else
        {
            <div class="col-lg-12 mb-3">
                <div class="col-12">
                    <div class="col-12">
                        <label class="btn btn-primary btn-block" for="my-file-selector">
                            <input id="my-file-selector" name="file" type="file" style="display:none"
                                   onchange="realUrl(this)">
                            Wybierz zdjęcie
                        </label>
                    </div>
                    <div class="col-12 text-center">
                        <span class='label label-info font-weight-bold' id="upload-file-info"></span>
                    </div>
                </div>
                <div class="col-12">
                    <div class="col-12 mt-2 mb-2">Nowy obrazek</div>
                    <div class="col-12 text-center">
                        <img id="userNewImage" src="@Url.ImagesOtherPath("mNTZ.png")" class="img-fluid" alt="Twoje zdjęcie" />
                    </div>
                </div>
            </div>
        }
    </div>

    <button type="submit" class="btn btn-primary btn-block">Dodaj</button>
}


<div id="modal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Wykryty Spam</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Przykro nam, ale ten tekst jest podejrzany o bycie spamem proszę wprowadzić inny</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Zamknij</button>
            </div>
        </div>
    </div>
</div>


<script>
    function realUrl(input) {
        $('#upload-file-info').html(input.files[0].name);
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                console.log(e.target.result);
                $('#userNewImage').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }


</script>